%% Information
% Standard MWT mutant habituation graph from Conny?s dissertation has 
%   3 graphs. 
% A ? Curve %, 
% B - tap response reversal probability and 
% C ? acceleration probability. 
% 
% The summary graph is assembled by ?SummaryAssemble1.m?
% 
% ~~~~~~~~
% Graph A 
% ~~~~~~~~
% needs data from:
% pC = fullfile(pData_Strain,strain,'Etoh sensitivity','InitialEtohSensitivityPct','data.mat');
% 
% which comes from ?InitialEtohSensitivityPct.m?, which pulls data from ?DataTrv.mat? that?s generated by Dance_ShaneSpark4.m.
% 
% ~~~~~~~~
% Graph B 
% ~~~~~~~~
% needs data from:
% p = fullfile(pData_Strain,strain,'TWR/Dance_ShaneSpark4/Dance_ShaneSpark4.mat');
% which is generated by Dance_ShaneSpark4.m.
% 
% ~~~~~~~~
% Graph C 
% ~~~~~~~~
% needs data from
% p = fullfile(pData_Strain,strain,'TAR/Dance_rType/data.mat');
% 
% which comes from Dance_rType, and the program is here
% 	accCurve_allstrains_20161022.m
% 
% Data = Dance_rType(pData,'pSave',pSave,'genotype',genotype);
% 
% 
% Strategy:
% ?	Start with ShaneSpark, 
% ?	Initial sensitivity
% ?	rType
% -------------------------------------------------------------------------

%% INITIALIZING -----------------------------------------------------------
clc; clear; close all;
addpath('/Users/connylin/Dropbox/Code/Matlab/Library/General');
pM = setup_std(mfilename('fullpath'),'RL','genSave',true);
addpath(pM);

% input paths (Conny's default)
pNewData = '/Volumes/COBOLT/MWT_New';
pDataBase = '/Volumes/COBOLT/MWT';
pPaper = '/Users/connylin/Dropbox/CA Publications/Manuscript RL Alcohol hab model slo1';
pSave = fileparts(pM);

% paths (program)
p = mfilename('fullpath');
p1 = fileparts(p);
addpath_allsubfolders(p1);
clear functionfoldername p1 p;

%--------------------------------------------------------------------------


%% QUERY DATABASE ---------------------------------------------------------
% get database
p = sprintf('%s/%s',pDataBase,'MWTDB.mat');
load(p);
clear p;
DB = MWTDB.text; % get experiment database

% query conditions
condStrains = {...
    'BZ142'
    'NM1630'
    'NM1968'
    'JPS428'
    'JPS429'
    'HKK1165'
    'HKK796'
    'VG902'
    'VG903'        
    };

% for each strains, find the experiment sets
DB = MWTDB.text;
% keep only 10s ISI
DB(~ismember(DB.rc,'100s30x10s10s'),:) = []; 
% get exp for each strain 
ExpSets = cell(size(condStrains));
eu = unique(DB.expname); % unique experiment list
for si = 1:numel(condStrains)
    strainname = condStrains{si};
    condGN = {'N2','N2_400mM',strainname,sprintf('%s_400mM',strainname)};
    % set qualifying matrix for unique experiment list
    m = false(size(eu,1),numel(condGN));
    for gi = 1:numel(condGN)
        % index to mwt with the group name
        i = ismember(DB.groupname,condGN(gi));
        % find experiment that has the group name
        u = unique(DB.expname(i));
        % index to experiment list
        j = ismember(eu,u);
        % mark that experiment as containing the group
        m(j,gi) = true;
    end
    % get index to qualified experiments on the list
    i = sum(m,2) == numel(condGN);
    % keep only those experiments
    j = ismember(DB.expname,eu(i));
    D = DB(j,:);
    % remove plates that do not have the targeted group names
    i = ismember(D.groupname,condGN);
    D(~i,:) = [];
    % put the dataset in the file
    ExpSets{si} = D;
    % export in csv
    filename = sprintf('%s/%s_experiment info.csv',pSave,strainname);
    writetable(D,filename);
end
%--------------------------------------------------------------------------

return
%% program (to do)

ExpSets

for si = 1:numel(condStrains)
    strainname = condStrains{si};
    MWTSet = Dance_ShaneSpark4(pMWT,pS);

end







































